### ISSUE TITLE
Planning to implement front-end for Campus Recruitment Project

### ISSUE THREAD

**Issue by Riya-Singhal15** [einn-software/Campus_Recruitment_App#57]
### Pages to be implemented

    

  - [x]  Home page   (#59 created commit no- 40458aa68e77e728361a650a159e3c689958b7a5)

**Login Pages**    (2 days)        

  - [ ]  Admin Login  (#58 will be created by 14-06-2020)

  - [ ] Tpo Login  (#58 will be created by 14-06-2020)

  - [ ] Student Login  (#58 will be created by 15-06-2020)

  - [ ] College Login  (#58 will be created by 15-05-2020)

**Register Pages**   

   - [x] Admin Register (#60 created)

   - [x] Tpo Register (#60 created)

   - [x] Student Register (#60 created)

   - [x]  College Register (#60 created)

**Dashboard Pages**  (3 days)

   - [ ] Admin Dashboard  (#61 will be created by 14-06-2020)

   - [ ]  College Dashboard  (#61 will be created by 15-06-2020)
   - [ ]  Student Dashboard  (#61 will be created by 16-06-2020)

 **Result Page**     (1 day)

      
- [ ] Result (will be created by 21-06-2020)

 **Instructions Page**       (1 day)
 

- [ ] Instruction (will be created by 22-06-2020)

 **Examination page**      (3 days)

- [ ] Examination ( will be created by 20-06-2020)

**Password Reset Pages** (2 days)

- [ ] Password Reset Pages for Admin, College, Tpo and Student (will be created by 26-06-2020)

**Comment by Riya-Singhal15** [comment]
Front end work is not implemented yet due to changes in the backend, so I'm closing this issue and I will open a new ticket when the work on the frontend will be started.
