### ISSUE TITLE
Weekly Planning (18th of May - 22nd of May)

### ISSUE THREAD

**Issue by Riya-Singhal15** [einn-software/Campus_Recruitment_App#70]
The work I have to do this week is as follows :-
**Frontend Pages to be implemented**

**Result Page** (1 day)

- [ ] Result (will be created by 21-06-2020)

**Instructions Page** (1 day)

- [ ] Instruction (will be created by 22-06-2020)

**Examination page** (3 days)

- [ ] Examination (#73 will be created by 20-06-2020)

**Backend Changes**
I will do some of these changes with my daily work.

- [x] Changes in the Testing Files

- [x] Changes in the API whenever someone stuck on that

- [x] Changes in the API documentation (#68 )

- [x] Adding comments in all the files wherever required (will be completed today)

- [x] Changes to be made in API responses (#67 will be completed today)

**Comment by Riya-Singhal15** [comment]
Front end work is not implemented yet due to changes in the backend, so I'm closing this issue and I will open a new ticket when the work on the frontend will be started.
